= Spearal Spring

== What is Spearal?

Spearal is a compact binary format for exchanging arbitrary complex data between various endpoints such as Java EE, JavaScript / HTML, Android and iOS applications.

Spearal-Spring is an extension of Spearal-Java which implements the necessary integration classes to use Spearal in Spring MVC REST client and server applications.

== How to get and build the project?

First, you need to get, build and install Spearal-Java:

[source,bash]
----
$ git clone https://github.com/spearal/spearal-java.git
$ cd spearal-java
$ ./gradlew install
----

Then, you can build Spearal Spring:

[source,bash]
----
$ cd ..
$ git clone https://github.com/spearal/spearal-spring.git
$ cd spearal-spring
$ ./gradlew build
----

The library can then be found in the `build/libs` directory.


== How to use the library?

=== Server-side

The library is available in the Maven central repository, so with Maven or Gradle you simply have to reference 
the dependency on the library in your build system:

[source,xml]
.Maven
----
<dependency>
	<groupId>org.spearal</groupId>
	<artifactId>spearal-spring</artifactId>
	<version>0.2.0</version>
</dependency>
----

[source,java]
.Gradle
----
compile 'org.spearal:spearal-spring:0.2.0'
----

Spearal-Spring can then be configured with Spring XML Config or Java Config.

==== XML Config

To configure the Spring MVC integration (REST message converter, etc.):

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:spearal="http://www.spearal.io/config"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans.xsd
        http://spearal.io/config
        http://spearal.io/public/spring/1.0/spearal-config-1.0.xsd">
        
   	<bean id="spearalFactory" class="org.spearal.DefaultSpearalFactory"/>
    
    <spearal:rest/>
</beans>
----

NOTE: You have to declare one single bean of type `SpearalFactory` that contains the Spearal configuration.

If you want to actually change something in the default configuration, you can use a factory bean to create 
the `SpearalFactory` and call `spearalFactory.configure(new SomeOption());`.

The JPA integration (EntityManager proxying, etc.) can be configured with:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:spearal="http://www.spearal.io/config"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans.xsd
        http://spearal.io/config
        http://spearal.io/public/spring/1.0/spearal-config-1.0.xsd">
    
    <spearal:jpa/>
</beans>
----


==== Java Config

To configure the Spring MVC integration (REST message converter, etc.), use the annotation
`@EnableSpearalRest` in a `@Configuration` class:

[source,java]
----
@Configuration
@EnableWebMvc
@EnableSpearalRest
public class PersonWebConfig extends WebMvcConfigurerAdapter {
	
	@Bean
	public SpearalFactory spearalFactory() {
		return new DefaultSpearalFactory();
	}
	
	...
	// Configure resources
}
----

Note that we declare the `SpearalFactory` here and that we could do additional setup.

To configure the JPA integration, use `@EnableSpearalJpa`:

[source,java]
----
@Configuration
@EnableTransactionManagement
@EnableSpearalJpa
public class PersonJpaConfig {
	
    @Bean
    public DataSource dataSource() {
        ...
    }
    
    @Bean
    public LocalContainerEntityManagerFactoryBean entityManagerFactory() {
    	...
    }
    
    @Bean
    public PlatformTransactionManager transactionManager(EntityManagerFactory emf) {
    	...
    }
}
----

=== Client-side (Android)

When using Spring-Android REST, there is no application context so you have to wire
the various elements manually.

Most operations involve a `RestTemplate`, so the setup will be done like this:

[source,java]
----
SpearalFactory spearalFactory = new DefaultSpearalFactory();
RestTemplate restTemplate = new RestTemplate();
restTemplate.getMessageConverters().add(new SpearalMessageConverter(spearalFactory));
----

Of course in most cases you will use more than one `RestTemplate` so you will have to share the same `SpearalFactory`
accross the whole application.
It's recommended to build the `SpearalFactory` inside a singleton and reuse it everywhere in the app:

[source,java]
----
public class SpearalFactoryHolder {
	
	private static SpearalFactory spearalFactory = null;
	
	public static SpearalFactory getInstance() {
		if (spearalFactory != null)
			return spearalFactory;
		
		spearalFactory = new DefaultSpearalFactory();
		spearalFactory.getContext().configure(new PackageTranslatorAliasStrategy(
			"org.spearal.examples.android", "org.spearal.examples.server.spring"));
		return spearalFactory;
	}
}
----

Here we also configure a specific class alias strategy in the factory. Then use the factory from anywhere:

[source,java]
----
RestTemplate restTemplate = new RestTemplate();
restTemplate.getMessageConverters().add(
	new SpearalMessageConverter(SpearalFactoryHolder.getInstance())
);
----

==== Using property filters

You can set property filters manually with http headers, but it's a lot more convenient to use the specific wrapper object `SpearalEntity`:

[source,java]
----
SpearalPropertyFilterBuilder filter = 
	SpearalPropertyFilterBuilder.of(Person.class, "name", "description")
        
SpearalEntity<Object> filterEntity = new SpearalEntity<Params>(
	SpearalFactoryHolder.getInstance(), null, null, filter);
ResponseEntity<Object> responseEntity = 
	restTemplate.exchange(url, HttpMethod.GET, filterEntity, resultClass, params);
Object result = responseEntity.getBody();
----

The `SpearalPropertyFilterBuilder` is a simple builder for `SpearalPropertyFilter` objects. It makes possible to build and store instances
of property filters ahead of serialization. The builder will then convert the specified values to a correct HTTP header string, taking
care of applicable class and property aliases.

The first argument (client filter) will be applied during serialization of the client object to the server. The second Object (server filter)
will be applied during serialization of the server result from the server to the client. This second one is converted as a String and passed
to the server as HTTP header. It is then transmitted from the request to the response handler by a Spring `ResponseBodyAdvice`.
